# Generated by Django 4.2.13 on 2024-06-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
