# Generated by Django 4.2.13 on 2024-07-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_post_image_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
