# Generated by Django 4.2.13 on 2025-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
